src/DriveDrop.Web/DriveDrop.Web/ViewModels/Address.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DriveDrop.Web.ViewModels
{
    public class Address 
    {
        public int Id { get;  set; }
        [JsonProperty("street")]
        public String Street { get;  set; }

        public String City { get;  set; }

        public String State { get;  set; }

        public String Country { get;  set; }

        public String ZipCode { get;  set; }

        public String Phone { get;  set; }
        public String Contact { get;  set; }


        public Double Latitude { get;  set; }
        public Double Longitude { get;  set; }
        protected Address() { }

        
    }
}

src/DriveDrop.Web/DriveDrop.Web/Controllers/SenderController.cs
using DriveDrop.Web.Infrastructure;
using DriveDrop.Web.Services;
using DriveDrop.Web.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.eShopOnContainers.BuildingBlocks.Resilience.Http;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using static DriveDrop.Web.Services.PasswordAdvisor;

namespace DriveDrop.Web.Controllers
{
    [Authorize]
    public class SenderController : Controller
    {
        private readonly IPictureService _pictureService;

        private IHttpClient _apiClient;
        private readonly string _remoteServiceBaseUrl;
        private readonly string _remoteServiceCommonUrl;
        private readonly string _remoteServiceShippingsUrl;
        private readonly string _remoteServiceRatesUrl;
        private readonly string _remoteServiceIdentityUrl;
        private readonly IOptionsSnapshot<AppSettings> _settings;
        private readonly IHttpContextAccessor _httpContextAccesor;
        private readonly IIdentityParser<ApplicationUser> _appUserParser;

        private readonly IHostingEnvironment _env;


        public SenderController(
              IPictureService pictureService,
            IOptionsSnapshot<AppSettings> settings, IHttpContextAccessor httpContextAccesor,
            IHttpClient httpClient, IIdentityParser<ApplicationUser> appUserParser,
            IHostingEnvironment env)
        {

            _remoteServiceCommonUrl = $"{settings.Value.DriveDropUrl}/api/v1/common/";
            _remoteServiceBaseUrl = $"{settings.Value.DriveDropUrl}/api/v1/sender";
            _remoteServiceShippingsUrl = $"{settings.Value.DriveDropUrl}/api/v1/shippings";
            _remoteServiceRatesUrl = $"{settings.Value.DriveDropUrl}/api/v1/rates/";
            _remoteServiceIdentityUrl = $"{settings.Value.IdentityUrl}/account/";

            _settings = settings;
            _httpContextAccesor = httpContextAccesor;
            _apiClient = httpClient;
            _appUserParser = appUserParser;

            _env = env;

            _pictureService = pictureService;

        }

        public IActionResult Index()
        {
            return View();
        }


        public async Task<IActionResult> InitializeReview(int id)
        {

            var user = _appUserParser.Parse(HttpContext.User);
            var token = await GetUserTokenAsync();

            var currenUserUri = API.Sender.GetByUserName(_remoteServiceBaseUrl, user.Email);
            var currentUserString = await _apiClient.GetStringAsync(currenUserUri, token);
            var currentUser = JsonConvert.DeserializeObject<CurrentCustomerModel>((currentUserString));
            if (currentUser == null)
            {
                return NotFound();
            }
            var package = currentUser.ShipmentSenders.Where(x => x.Id == id).FirstOrDefault();
            if (package == null)
            {
                return NotFound();
            }



            var iUri = API.Rating.InitializeReview(_remoteServiceBaseUrl, id);
            var iString = await _apiClient.GetStringAsync(currenUserUri, token);
            var review = JsonConvert.DeserializeObject<ReviewModel>((iString));


            return RedirectToAction("ShippingDetails", new { id = package.Id });
        }


        public async Task<IActionResult> ShippingDetails(int id)
        {
            var user = _appUserParser.Parse(HttpContext.User);
            var token = await GetUserTokenAsync();

            var currenUserUri = API.Sender.GetByUserName(_remoteServiceBaseUrl, user.Email);
            var currentUserString = await _apiClient.GetStringAsync(currenUserUri, token);
            var currentUser = JsonConvert.DeserializeObject<CurrentCustomerModel>((currentUserString));

            if (currentUser == null)
            {
                return NotFound();
            }
            var shipping = currentUser.ShipmentSenders.Where(x => x.Id == id).FirstOrDefault();

            //var allnotassignedshipings = API.Shipping.GetById(_remoteServiceShippingsUrl, id);

            //var dataString = await _apiClient.GetStringAsync(allnotassignedshipings, token);

            //var shippings = JsonConvert.DeserializeObject<Shipment>((dataString));
            //if (shippings == null)
            //    return View(new Shipment());
            return View(shipping);

        }

        public async Task<IActionResult> Shippings(int id)
        {
            //call shipping api service
            var user = _appUserParser.Parse(HttpContext.User);
            var token = await GetUserTokenAsync();

            var currenUserUri = API.Sender.GetByUserName(_remoteServiceBaseUrl, user.Email);
            var currentUserString = await _apiClient.GetStringAsync(currenUserUri, token);
            var currentUser = JsonConvert.DeserializeObject<CurrentCustomerModel>((currentUserString));

            if (currentUser == null)
            {
                return NotFound();
            }
            ViewBag.Id = currentUser.Id;
            var shippings = currentUser.ShipmentSenders;

            return View(shippings);

        }



        public async Task<IActionResult> Result(int? id)
        {

            var user = _appUserParser.Parse(HttpContext.User);
            var token = await GetUserTokenAsync();

            var currenUserUri = API.Sender.GetByUserName(_remoteServiceBaseUrl, user.Email);
            var currentUserString = await _apiClient.GetStringAsync(currenUserUri, token);
            var currentUser = JsonConvert.DeserializeObject<CurrentCustomerModel>((currentUserString));

            if (currentUser == null)
            {
                return NotFound();
            }


            if (string.IsNullOrWhiteSpace(currentUser.PersonalPhotoUri))
                currentUser.PersonalPhotoUri = _settings.Value.ImagesUrl + "profile-icon.png";

            currentUser.PersonalPhotoUri = _settings.Value.PicBaseUrl.Replace("[0]", System.Net.WebUtility.UrlEncode(currentUser.PersonalPhotoUri));


            currentUser.CustomerStatus = currentUser.CustomerStatus.ToTitleCase();
            return View(currentUser);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateInfo(CustomerInfoModel model, IFormFile photoUrl)
        {
            var result = "Info updated";
            if (ModelState.IsValid)
            {
                try
                {
                    var token = await GetUserTokenAsync();
                    var fileName = "";
                    if (photoUrl != null)                    
                         fileName = await SaveFile(photoUrl, "sender");

                        if (!string.IsNullOrWhiteSpace(fileName))
                            model.PhotoUrl = fileName;
                        else
                            model.PhotoUrl = model.PersonalPhotoUri;
                    

                    var user = _appUserParser.Parse(HttpContext.User);
                    
                    var getUserUri = API.Sender.GetByUserName(_remoteServiceBaseUrl, user.Email);
                    var userString = await _apiClient.GetStringAsync(getUserUri, token);
                    var customer = JsonConvert.DeserializeObject<CurrentCustomerModel>(userString);
                    if (customer != null)
                    {
                        var updateInfo = API.Sender.UpdateInfo(_remoteServiceBaseUrl);

                        var response = await _apiClient.PostAsync(updateInfo, model, token);
                        if (response.StatusCode == System.Net.HttpStatusCode.InternalServerError)
                        {
                            //throw new Exception("Error creating Shipping, try later.");

                            ModelState.AddModelError("", "Error creating Shipping, try later.");

                        }
                        else
                            ModelState.AddModelError("", "Info Updated!");
                    }
                }
                catch (DbUpdateException ex)
                {
                    //Log the error (uncomment ex variable name and write a log.
                    var error = string.Format("Unable to save changes. " +
                        "Try again, and if the problem persists " +
                        "see your system administrator. {0}", ex.Message);

                    ModelState.AddModelError("", error);
                    result = error;
                }
            }

            return RedirectToAction("result", new { id = model.Id });
        }

        public async Task<IActionResult> NewShipping(int id)
        {


            var model = new NewShipment();
            await PrepareCustomerModel(model);
            model.CustomerId = id;

            await PrepareCustomerAddresses(model, id);


            ViewBag.PhotoUrl = _settings.Value.ImagesUrl + "profile-icon.png";


            ViewBag.PersonalPhotoUri = _settings.Value.PicBaseUrl.Replace("[0]", System.Net.WebUtility.UrlEncode(ViewBag.PhotoUrl));


            return View(model);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> NewShipping(NewShipment c, IFormFile photoUrl)
        {

            try
            {
                ModelState.Clear();

                //foreach (var state in ViewData.ModelState.Values.Where(x => x.Errors.Count > 0))
                //{
                //    var tt = state.Errors.ToString();
                //    ModelState.AddModelError("", state.Errors[0].ErrorMessage);
                //}
                if (c.PickupAddressId == 0)

src/DriveDrop.Web/DriveDrop.Web/Views/Sender/Address.cshtml
@model IEnumerable<DriveDrop.Web.ViewModels.AddressModel>
    @{
        ViewData["Title"] = "Details";

    var addresses = Model;
    }

    <div class="side-2">



        @await Html.PartialAsync("CustomerNavigation",(int)@ViewBag.Id)


    </div>
    <div class="center-2">


        <div class="page account-page address-list-page">
            <div class="page-title">
                <h1>My addresses</h1>
            </div>
            <div class="page-body">
                @using (Html.BeginForm())
                {
                @Html.AntiForgeryToken()
                    <div class="address-list">
                        <div class="page-title">
                            <h4>Default Address</h4>
                        </div>
                        @foreach (var address in addresses.Where(x => x.TypeAddress.ToLower() == "home" || x.TypeAddress == "default"))
                        {

                            <div class="section address-item">
                                <div class="title"> 
                                    <strong>@address.Contact @address.Phone</strong>
                                </div>
                                <ul class="info">

                                    <li class="address1">
                                        Street
                                        @address.Street
                                    </li>
                                    <li class="city-state-zip">
                                        @address.City, @address.State, @address.ZipCode
                                    </li>
                                    <li class="country">
                                        @address.Country
                                    </li>
                                </ul>
                                <div class="buttons">
                                    @*<input type="button" class="button-2 edit-address-button" onclick="location.href = '@(Url.Action("EditAddress","Sender", new {id = address.Id}))'" value="Edit" />*@
                                    <input type="button" class="button-2 delete-address-button" onclick="deletecustomeraddress(@(address.Id))" value="Delete" />
                                </div>
                            </div>
                        }
                    </div>
                            <div class="address-list">
                                <div class="page-title">
                                    <h4>Pickup Address</h4>
                                </div>


                                @foreach (var address in addresses.Where(x => x.TypeAddress.ToLower() == "pickup" ))
                                {

                                    <div class="section address-item">
                                        <div class="title"> 
                                        <strong>@address.Contact @address.Phone</strong>
                                    </div>
                                    <ul class="info">

                                        <li class="address1">
                                            Street
                                            @address.Street
                                        </li>
                                        <li class="city-state-zip">
                                            @address.City, @address.State, @address.ZipCode
                                        </li>
                                        <li class="country">
                                            @address.Country
                                        </li>
                                    </ul>
                                    <div class="buttons">
                                        @*<input type="button" class="button-2 edit-address-button" onclick="location.href = '@(Url.Action("EditAddress","Sender", new {id = address.Id}))'" value="Edit" />*@
                                        <input type="button" class="button-2 delete-address-button" onclick="deletecustomeraddress(@(address.Id))" value="Delete" />
                                    </div>
                                </div>
                                }
                            </div>

                            <div class="address-list">
                                <div class="page-title">
                                    <h4>Dropoff Address</h4>
                                </div>


                                @foreach (var address in addresses.Where(x => x.TypeAddress.ToLower() == "drop"))
                                {

                                    <div class="section address-item">
                                        <div class="title"> 
                                            <strong>@address.Contact @address.Phone</strong>
                                        </div>
                                        <ul class="info">

                                            <li class="address1">
                                                Street
                                                @address.Street
                                            </li>
                                            <li class="city-state-zip">
                                                @address.City, @address.State, @address.ZipCode
                                            </li>
                                            <li class="country">
                                                @address.Country
                                            </li>
                                        </ul>
                                        <div class="buttons">
                                            @*<input type="button" class="button-2 edit-address-button" onclick="location.href = '@(Url.Action("EditAddress","Sender", new {id = address.Id}))'" value="Edit" />*@
                                            <input type="button" class="button-2 delete-address-button" onclick="deletecustomeraddress(@(address.Id))" value="Delete" />
                                        </div>
                                    </div>
                                }
                            </div>

                    <script type="text/javascript">
                        function deletecustomeraddress(addressId) {
                            if (confirm('Are you sure?')) {
                                var postData = {
                                    addressId: addressId
                                };
                                alert(addressId);
                                addAntiForgeryToken(postData);
                                alert(addressId);
                                $.ajax({
                                    cache: false,
                                    type: 'POST',
                                    url: '/Sender/AddressDelete',
                                    data: postData,
                                    dataType: 'json',
                                    success: function (data) {
                                        location.href = data.redirect;
                                    },
                                    error: function (xhr, ajaxOptions, thrownError) {
                                        alert('Failed to delete');
                                    }
                                });
                            }
                        }
                    </script>
               }
                <div class="add-button">
                    <input type="button" class="button-1 add-address-button" onclick="location.href='/sender/addressadd/@(ViewBag.Id)'" value="Add new" />
                </div>
            </div>
        </div>


    </div>

src/DriveDrop.Web/DriveDrop.Web/Views/Sender/CustomerNavigation.cshtml
@model int
<div class="block block-account-navigation">
    <div class="title">
        <strong>My account</strong>
    </div>
    <div class="listbox">
        <ul class="list">

            <li class="customer-info">
                @Html.ActionLink("My Personal info", "result", "sender", new { id = Model }, null)
                 
            </li>
            <li class="customer-info"> 
                @Html.ActionLink("My Address", "Address", "sender", new { id = Model }, null)
            </li>
            <li class="customer-info"> 
                @Html.ActionLink("My Packages", "Shippings", "sender", new { id = Model }, null)
            </li>

            <li class="customer-info">
                @Html.ActionLink("Add new Packages", "NewShipping", "sender", new { id = Model }, null) 
            </li>
            <li class="change-password">
                <a href="/customer/changepassword" class="inactive">Change password</a>
            </li>


        </ul>
    </div>
</div>

src/DriveDrop.Web/DriveDrop.Web/Views/Sender/PostToPayPalAsync.cshtml
@model DriveDrop.Web.ViewModels.Paypal
@{
    ViewData["Title"] = "PostToPayPal";
}

<form id="frm" action="@(ViewBag.actionURL)">

    <input asp-for="cmd" hidden />
    <input asp-for="business" hidden />
    <input asp-for="no_shipping" hidden />
    <input asp-for="upload" hidden />
    <input asp-for="item_name" hidden />
    <input asp-for="amount" hidden />
    <input asp-for="price_per_item" hidden />
    <input asp-for="quantity" hidden />
    <input asp-for="discount" hidden />
    <input asp-for="custom" hidden />
    <input asp-for="custom" hidden />
    <input asp-for="bn" hidden />
    <input asp-for="no_note" hidden />
    <input asp-for="currency_code" hidden />
    <input asp-for="invoice" hidden />
    <input asp-for="rm" hidden />
    <input asp-for="address_override" hidden />
    <input asp-for="first_name" hidden />
    <input asp-for="last_name" hidden />
    <input asp-for="address1" hidden />
    <input asp-for="address2" hidden />
    <input asp-for="city" hidden />
    @*<input asp-for="State" hidden />*@
    <input asp-for="country" hidden />
    <input asp-for="zip" hidden />
    <input asp-for="email" hidden />
    <input asp-for="returN" hidden />
    <input asp-for="cancel_return" hidden />
    <input asp-for="notify_url" hidden />

</form>

<div class="center-block bg-primary text-center" id="bar-notification">
    <h3>Redirecting to Paypal...</h3>
</div>



    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
        <script>
            $(this.document).ready(function () {
                var frm = $("form");
                frm.submit();
            });
        </script>
    }

src/DriveDrop.Web/DriveDrop.Web/Views/Sender/Return.cshtml
@{
    ViewData["Title"] = "Return";

    var option = new DriveDrop.Web.ViewModels.TwoParameterModel { Id = (int)@ViewBag.CustomerId, Option = "NewShipping" };
}


<section class="sender-desh">
    <div class="container">
        <div class="main-cont">
            <div class="row">

                @await Html.PartialAsync("CustomerNavigation", option)
                <div id="content" class="col-sm-9">
                    <div id="gig-information" class="sender-form">
                        <h3 class="blue-head active">New Package</h3>
                        <div class="form-body">
                            <div class="profile-form">
                                <div class="row">
                                    <div class="page account-page address-list-page">
                                        <div class="page-title">
                                            <h1>My Account - New Package</h1>
                                        </div>
                                        <div class="page-body">
                                            <h2>Shipping Have Been Processed</h2>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
        </section>
            


 

                                    @*<button onclick="htmlSendNotice('dddddddddddddddddddddddd')">sendButton</button>
                                <button id="sendButton">sendButton</button>*@

                                    @section Scripts {
                                        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
                                        <script>



                                            htmlSendNotice('dddddddddddddddddddddddd');


                                        </script>
                                    }

src/DriveDrop.Web/DriveDrop.Web/Views/Sender/Shippings.cshtml
@model IEnumerable<DriveDrop.Web.ViewModels.Shipment>
@{


    var option = new DriveDrop.Web.ViewModels.TwoParameterModel { Id = (int)@ViewBag.Id, Option = "Shippings" };
}


<section class="sender-desh">
    <div class="container">
        <div class="main-cont">
            <div class="row">

                @await Html.PartialAsync("CustomerNavigation", option)

                <div id="content" class="col-sm-9">
                    <div id="gig-information" class="sender-form">
                        <h3 class="blue-head active">My Packages</h3>
                        <div class="form-body">
                            <div class="profile-form">
                                <div class="row">

                                    @if (Model != null && Model.Any())
                                    {

                                        <table class="table table-responsive table-hover">
                                            <thead>
                                                <tr>

                                                    <td>Priority</td>
                                                    <td>Package #</td>
                                                    <td>Driver</td>
                                                    <td>Status</td>
                                                    <td>Status Date </td>
                                                    <td>Created Date </td>
                                                    <td>Security Code</td>
                                                </tr>
                                            </thead>
                                            <tbody>


                                                @foreach (var shipping in Model.OrderBy(x => x.PriorityTypeId))
                                                {
                                                    <tr>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => shipping.PriorityType.Name)
                                                        </td>
                                                        <td>
                                                            @Html.ActionLink(shipping.IdentityCode, "ShippingDetails", "sender", new { id = shipping.Id })
                                                        </td>
                                                        <td>

                                                            @if (shipping.Driver != null)
                                                            {

                                                                var driver = shipping.Driver.FirstName + " " + shipping.Driver.LastName;

                                                                @*@Html.ActionLink(driver, "details", "admin", new { id = shipping.DriverId })*@
                                                                @Html.ActionLink(driver, "ShippingDetails", "sender", new { id = shipping.Id })

                                                            }
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => shipping.ShippingStatus.Name)
                                                        </td>
                                                        <td class="align-center">
                                                            @if (shipping.PackageStatusHistories != null)
                                                            {
                                                            @Html.DisplayFor(modelItem => shipping.PackageStatusHistories.OrderByDescending(x => x.StatusDate).FirstOrDefault().StatusDate)
                                                            }
                                                            else
                                                            { 
                                                                <label>@DateTime.Today</label>

                                                            }

                                                        </td>
                                                        <td class="align-center">
                                                            @Html.DisplayFor(modelItem => shipping.ShippingCreateDate)


                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => shipping.SecurityCode)
                                                        </td>

                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    }
                                </div>
                                <div class="post-gig">
                                    <input type="submit" value="Add New" name="save-info-button" class="bttn save-customer-info-button"  onclick="location.href='/sender/NewShipping/@(ViewBag.Id)'"/>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
        </section>
                     